version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: construction_docs_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "5002:3306"