CREATE TABLE IF NOT EXISTS acts
(
    id      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    month   VARCHAR(20) NOT NULL,
    section VARCHAR(20) NOT NULL,
    price   DOUBLE,
    status  VARCHAR(30) NOT NULL
);